# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"addition": "00_arithmatic.ipynb",
         "subtraction": "00_arithmatic.ipynb",
         "multiplication": "00_arithmatic.ipynb",
         "division": "00_arithmatic.ipynb"}

modules = ["arithmatic.py"]

doc_url = "https://muellerzr.github.io/odsc_demo/"

git_url = "https://github.com/muellerzr/odsc_demo/tree/main/"

def custom_doc_links(name): return None
