# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_arithmatic.ipynb (unless otherwise specified).

__all__ = ['addition', 'subtraction', 'multiplication', 'division']

# Cell


# Cell
def addition(a:(int,float),b:(int,float)) -> (int,float):
    "Adds two numbers together"
    return a+b

# Cell
def subtraction(a:(int,float),b:(int,float)) -> (int,float):
    "Subtracts b from a"
    return b-a

# Cell
def multiplication(a:(int,float), b:(int,float)) -> (int,float):
    "Multiples `a` and `b`"
    return a*b

# Cell
def division(a:(int,float),b:(int,float)) -> (int,float):
    "Divides a by b"
    return a / b